# -*- coding: utf-8 -*-
"""bert_entity_typing_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpE6RyDBqgirjEl5GTMATgnvraVBlNHv

# BERT Entity Typing — Training Notebook (Colab)

Trains a BERT classifier to predict an entity's `source_class` from its `description` text, using a yago-style JSON file (dict of iri -> entity).

## 1. Install dependencies
"""

!pip install -q transformers datasets scikit-learn

"""## 2. Get the data file into Colab

Option A: upload directly (file picker).
Option B: mount Google Drive and point `INPUT_PATH` at a file there (better if you'll reuse it across sessions).

"""

# Option B (alternative): mount Drive instead of the upload cell above
from google.colab import drive
drive.mount('/content/drive')

INPUT_PATH = '/content/drive/MyDrive/engineer.json'

"""## 3. Where to save outputs

Colab runtimes are ephemeral. If you want the trained model and results JSON to survive a disconnect, save them to Google Drive instead of `/content/...`. Mount Drive above and change these paths if so.

"""

OUTPUT_MODEL_DIR = "/content/drive/MyDrive/engineer_model_TEST"       # e.g. "/content/drive/MyDrive/thesis/bert_entity_typing_model"
OUTPUT_METRICS_PATH = "/content/drive/MyDrive/engineer_metrics_TEST.json"          # e.g. "/content/drive/MyDrive/thesis/training_results.json"
CHECKPOINT_DIR = "/content/drive/MyDrive/engineer_checkpoints_TEST"           # e.g. a Drive path, so a disconnect doesn't lose progress

"""## 4. Imports"""

import json
import random
from pathlib import Path
from collections import Counter

import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)

print("CUDA available:", torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

"""## 5. Config"""

MODEL_NAME = "answerdotai/ModernBERT-base"

MAX_LENGTH = 256
NUM_EPOCHS = 8
TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 32
LEARNING_RATE = 2e-5
TEST_SIZE = 0.10       # held-out test set
VAL_SIZE = 0.10        # held-out validation set
SEED = 42
MIN_EXAMPLES_PER_CLASS = 20  # classes with fewer examples than this are dropped

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed(SEED)

"""## 6. Load data"""

def load_dataset_from_json(path: str):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    texts, labels, iris = [], [], []
    skipped_no_desc = 0
    skipped_no_label = 0

    for iri, entity in data.items():
        desc = entity.get("description")
        label = entity.get("source_class")

        if not desc or not desc.strip():
            skipped_no_desc += 1
            continue
        if not label:
            print(f"No label for {iri}")
            skipped_no_label += 1
            continue

        texts.append(desc.strip())
        labels.append(label)
        iris.append(iri)

    print(f"Loaded {len(texts)} usable entities from {path}")
    if skipped_no_desc:
        print(f"  Skipped {skipped_no_desc} entities with no description")
    if skipped_no_label:
        print(f"  Skipped {skipped_no_label} entities with no source_class")

    return texts, labels, iris


texts, labels, iris = load_dataset_from_json(INPUT_PATH)
assert len(texts) > 0, "No usable entities found (need both description and source_class)."

"""## 7. Filter rare classes and build label mapping"""

class_counts = Counter(labels)
dropped_classes = {c for c, n in class_counts.items() if n < MIN_EXAMPLES_PER_CLASS}
if dropped_classes:
    print(f"Dropping {len(dropped_classes)} classes with < {MIN_EXAMPLES_PER_CLASS} examples: {sorted(dropped_classes)}")
    keep_idx = [i for i, l in enumerate(labels) if l not in dropped_classes]
    texts = [texts[i] for i in keep_idx]
    labels = [labels[i] for i in keep_idx]
    iris = [iris[i] for i in keep_idx]

unique_labels = sorted(set(labels))
label2id = {label: i for i, label in enumerate(unique_labels)}
id2label = {i: label for label, i in label2id.items()}
numeric_labels = [label2id[l] for l in labels]

print(f"Number of classes: {len(unique_labels)}")
print(f"Total examples after filtering: {len(texts)}")

"""## 8. Stratified train / val / test split"""

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    texts, numeric_labels,
    test_size=(TEST_SIZE + VAL_SIZE),
    stratify=numeric_labels,
    random_state=SEED,
)
relative_test_size = TEST_SIZE / (TEST_SIZE + VAL_SIZE)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels,
    test_size=relative_test_size,
    stratify=temp_labels,
    random_state=SEED,
)

print(f"Train: {len(train_texts)} | Val: {len(val_texts)} | Test: {len(test_texts)}")

"""## 9. Tokenize"""

from huggingface_hub import login
#login(token="Here would have been my token")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def make_dataset(texts_, labels_):
    ds = Dataset.from_dict({"text": texts_, "label": labels_})

    def tokenize_fn(batch):
        return tokenizer(
            batch["text"],
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH,
        )

    return ds.map(tokenize_fn, batched=True)

train_ds = make_dataset(train_texts, train_labels)
val_ds = make_dataset(val_texts, val_labels)
test_ds = make_dataset(test_texts, test_labels)

"""## 10. Model + Trainer setup"""

def compute_metrics_fn(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, preds)
    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average="macro", zero_division=0
    )
    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        labels, preds, average="weighted", zero_division=0
    )
    precision_micro, recall_micro, f1_micro, _ = precision_recall_fscore_support(
        labels, preds, average="micro", zero_division=0
    )

    return {
        "accuracy": acc,
        "precision_macro": precision_macro,
        "recall_macro": recall_macro,
        "f1_macro": f1_macro,
        "precision_weighted": precision_weighted,
        "recall_weighted": recall_weighted,
        "f1_weighted": f1_weighted,
        "precision_micro": precision_micro,
        "recall_micro": recall_micro,
        "f1_micro": f1_micro,
    }


model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(unique_labels),
    id2label=id2label,
    label2id=label2id,
)

training_args = TrainingArguments(
    output_dir=CHECKPOINT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=EVAL_BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    logging_strategy="epoch",
    save_total_limit=2,
    seed=SEED,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics_fn,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

"""## 11. Train
"""

print("Starting training...")
train_result = trainer.train()

"""## 12. Evaluate on validation set"""

val_metrics = trainer.evaluate(val_ds)
val_metrics

"""## 13. Evaluate on held-out test set"""

test_predictions = trainer.predict(test_ds)
test_logits = test_predictions.predictions
test_preds = np.argmax(test_logits, axis=-1)
test_true = test_predictions.label_ids

test_acc = accuracy_score(test_true, test_preds)
test_precision_macro, test_recall_macro, test_f1_macro, _ = precision_recall_fscore_support(
    test_true, test_preds, average="macro", zero_division=0
)
test_precision_weighted, test_recall_weighted, test_f1_weighted, _ = precision_recall_fscore_support(
    test_true, test_preds, average="weighted", zero_division=0
)

target_names = [id2label[i] for i in range(len(unique_labels))]
report_dict = classification_report(
    test_true, test_preds,
    target_names=target_names,
    zero_division=0,
    output_dict=True,
)

cm = confusion_matrix(test_true, test_preds, labels=list(range(len(unique_labels))))

print(f"Test accuracy: {test_acc:.4f} | Test F1 (macro): {test_f1_macro:.4f}")

"""## 16. Save model + tokenizer"""

Path(OUTPUT_MODEL_DIR).mkdir(parents=True, exist_ok=True)
trainer.save_model(OUTPUT_MODEL_DIR)
tokenizer.save_pretrained(OUTPUT_MODEL_DIR)
print(f"Model + tokenizer saved to: {OUTPUT_MODEL_DIR}")

"""## 17. Save results / metrics JSON"""

results = {
    "input_file": str(INPUT_PATH),
    "model_name": MODEL_NAME,
    "config": {
        "max_length": MAX_LENGTH,
        "num_epochs": NUM_EPOCHS,
        "train_batch_size": TRAIN_BATCH_SIZE,
        "eval_batch_size": EVAL_BATCH_SIZE,
        "learning_rate": LEARNING_RATE,
        "seed": SEED,
    },
    "data_summary": {
        "total_examples_used": len(texts),
        "num_classes": len(unique_labels),
        "classes": unique_labels,
        "class_counts": dict(class_counts),
        "dropped_classes_too_few_examples": sorted(dropped_classes),
        "train_size": len(train_texts),
        "val_size": len(val_texts),
        "test_size": len(test_texts),
    },
    "label2id": label2id,
    "train_summary": {
        "final_train_loss": train_result.training_loss,
    },
    "validation_metrics": {k.replace("eval_", ""): v for k, v in val_metrics.items()},
    "test_metrics": {
        "accuracy": test_acc,
        "precision_macro": test_precision_macro,
        "recall_macro": test_recall_macro,
        "f1_macro": test_f1_macro,
        "precision_weighted": test_precision_weighted,
        "recall_weighted": test_recall_weighted,
        "f1_weighted": test_f1_weighted,
    },
    "test_classification_report": report_dict,
    "test_confusion_matrix": cm.tolist(),
    "test_confusion_matrix_label_order": target_names
}

with open(OUTPUT_METRICS_PATH, "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"Metrics saved to: {OUTPUT_METRICS_PATH}")
print(f"Test accuracy: {test_acc:.4f} | Test F1 (macro): {test_f1_macro:.4f}")